const AUTH_PATH = '/auth'
const AUTH_PATH_GITHUB = AUTH_PATH + '/github'
const AUTH_PATH_LOGOUT = AUTH_PATH + '/logout'
const AUTH_SUCCESS_REDIRECT = '/'
const AUTH_FAILURE_REDIRECT = AUTH_PATH + '/failed'
const AUTH_LOGOUT_REDIRECT = AUTH_SUCCESS_REDIRECT

const DB_DOCUMENTS_COLLECTION = 'documents'
const DB_USERS_COLLECTION = 'users'

module.exports = {
  AUTH_PATH,
  AUTH_PATH_GITHUB,
  AUTH_PATH_LOGOUT,
  AUTH_SUCCESS_REDIRECT,
  AUTH_FAILURE_REDIRECT,
  AUTH_LOGOUT_REDIRECT,
  DB_DOCUMENTS_COLLECTION,
  DB_USERS_COLLECTION
}
