# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:9.3

before_script:
  - yarn install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

lint:
  script:
    - npm run lint

unit:
  script:
    - npm run test:coverage
