version: '3.3'
services:
  redis:
    image: 'redis:alpine'
  mongo:
    image: 'mongo'
  app:
    build: .
    volumes:
      - ./src:/usr/src/app/src
      - ./static:/usr/src/app/static
      - ./tests:/usr/src/app/tests
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis
    environment:
      - DVT_REDIS_HOST=redis
      - DVT_REDIS_PORT=6379
      - DVT_MONGO_URL=mongodb://mongo:27017/datavistech
      - DVT_STRIPE_PUBLISHABLE_KEY=${DVT_STRIPE_PUBLISHABLE_KEY}
      - DVT_STRIPE_SECRET_KEY=${DVT_STRIPE_SECRET_KEY}
